export const ITEM_lIST_REQUEST='ITEM_lIST_REQUEST'
export const ITEM_lIST_SUCCESS='ITEM_lIST_SUCCESS'
export const ITEM_lIST_FAIL='ITEM_lIST_FAIL'

export const ITEM_DETAIL_REQUEST='ITEM_DETAIL_REQUEST'
export const ITEM_DETAIL_SUCCESS='ITEM_DETAIL_SUCCESS'
export const ITEM_DETAIL_FAIL='ITEM_DETAIL_FAIL'